apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-data
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
